.PHONY: clean All

All:
	@echo "----------Building project:[ GuiltySpark - Debug ]----------"
	@cd "GuiltySpark" && "$(MAKE)" -f  "GuiltySpark.mk"
clean:
	@echo "----------Cleaning project:[ GuiltySpark - Debug ]----------"
	@cd "GuiltySpark" && "$(MAKE)" -f  "GuiltySpark.mk" clean
